<?php
/**
 * One-time web setup wizard
 * Generates php/config.php with site settings and hashed admin password.
 * Self-locks once config exists.
 */

$configPath = __DIR__ . '/php/config.php';

// Already configured — lock out
if (is_file($configPath)) {
    echo <<<'HTML'
    <!DOCTYPE html>
    <html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width">
    <title>Install — Already Configured</title>
    <style>
        * { margin: 0; box-sizing: border-box; }
        body { font-family: system-ui, sans-serif; display: grid; place-items: center; min-height: 100vh; background: #fafafa; color: #222; }
        .msg { text-align: center; }
        .msg h1 { font-size: 1.2rem; margin-bottom: .75rem; }
        .msg a { color: #111; }
    </style></head><body>
    <div class="msg">
        <h1>Already configured</h1>
        <p><code>php/config.php</code> exists. Delete it to re-run setup.</p>
        <p style="margin-top: 1rem"><a href="/admin">Go to admin</a> · <a href="/">Go to site</a></p>
    </div>
    </body></html>
    HTML;
    exit;
}

$error = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $siteUrl    = rtrim(trim($_POST['site_url'] ?? ''), '/');
    $siteTitle  = trim($_POST['site_title'] ?? '../');
    $siteDesc   = trim($_POST['site_description'] ?? '');
    $password   = $_POST['password'] ?? '';
    $confirm    = $_POST['password_confirm'] ?? '';

    if (!$siteUrl) {
        $error = 'Site URL is required.';
    } elseif (strlen($password) < 8) {
        $error = 'Password must be at least 8 characters.';
    } elseif ($password !== $confirm) {
        $error = 'Passwords do not match.';
    } else {
        $hash = password_hash($password, PASSWORD_BCRYPT);

        // Escape values for safe PHP source generation
        $safeTitle = addslashes($siteTitle);
        $safeUrl   = addslashes($siteUrl);
        $safeDesc  = addslashes($siteDesc);

        $configContent = <<<PHP
<?php
/**
 * Site configuration — generated by install.php
 */

return [
    'site_title'       => '{$safeTitle}',
    'site_url'         => '{$safeUrl}',
    'site_description' => '{$safeDesc}',
    'admin_password'   => '{$hash}',
    'content_dir'      => __DIR__ . '/../content',
    'content_folders'  => ['projects', 'explorations', 'notes'],
    'upload_targets'   => [
        'projects'     => __DIR__ . '/../content/projects',
        'explorations' => __DIR__ . '/../content/explorations',
        'notes'        => __DIR__ . '/../content/notes',
        'media'      => __DIR__ . '/../content/media',
        'prototypes' => __DIR__ . '/../content/prototypes',
    ],
];
PHP;

        // Ensure php/ directory exists
        if (!is_dir(__DIR__ . '/php')) {
            mkdir(__DIR__ . '/php', 0755, true);
        }

        file_put_contents($configPath, $configContent);

        // Create .htaccess if missing
        $htaccessPath = __DIR__ . '/.htaccess';
        if (!is_file($htaccessPath)) {
            $htaccess = <<<'HTACCESS'
RewriteEngine On
RewriteBase /

# Don't rewrite existing files or directories
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]

# Route everything else through index.php
RewriteRule ^ index.php [L]
HTACCESS;
            file_put_contents($htaccessPath, $htaccess);
        }

        // Create content directories if missing
        $contentDirs = ['content', 'content/projects', 'content/explorations', 'content/notes', 'content/media'];
        foreach ($contentDirs as $dir) {
            $path = __DIR__ . '/' . $dir;
            if (!is_dir($path)) {
                mkdir($path, 0755, true);
            }
        }

        $success = true;
    }
}

// Detect likely site URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost:8000';
$defaultUrl = $protocol . '://' . $host;

$esc = function($s) { return htmlspecialchars($s, ENT_QUOTES | ENT_HTML5, 'UTF-8'); };

?>
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width">
<title>Install — Setup</title>
<style>
    * { margin: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; display: grid; place-items: center; min-height: 100vh; background: #fafafa; color: #222; }
    .card { width: 380px; padding: 2rem; }
    h1 { font-size: 1.2rem; margin-bottom: 1.5rem; text-align: center; }
    form { display: flex; flex-direction: column; gap: .75rem; }
    label { font-size: .8rem; color: #555; text-transform: uppercase; display: flex; flex-direction: column; gap: .25rem; }
    input { padding: .6rem; border: 1px solid #ddd; border-radius: 4px; font-size: 1rem; font-family: inherit; }
    button { padding: .7rem; background: #111; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-size: 1rem; margin-top: .5rem; }
    .error { background: #fce4ec; border: 1px solid #f8bbd0; padding: .5rem .75rem; border-radius: 4px; font-size: .9rem; color: #c62828; }
    .success { text-align: center; }
    .success h1 { color: #2e7d32; }
    .success a { color: #111; display: inline-block; margin-top: 1rem; }
</style>
</head><body>

<?php if ($success): ?>
<div class="success">
    <h1>Setup complete</h1>
    <p><code>php/config.php</code> has been created.</p>
    <p><a href="/admin">Go to admin</a> · <a href="/">Go to site</a></p>
</div>
<?php else: ?>
<div class="card">
    <h1>Site Setup</h1>
    <?php if ($error): ?>
        <div class="error"><?= $esc($error) ?></div>
    <?php endif; ?>
    <form method="POST">
        <label>Site URL
            <input type="url" name="site_url" value="<?= $esc($_POST['site_url'] ?? $defaultUrl) ?>" required placeholder="https://example.com">
        </label>
        <label>Site Title
            <input type="text" name="site_title" value="<?= $esc($_POST['site_title'] ?? '../') ?>" required>
        </label>
        <label>Site Description
            <input type="text" name="site_description" value="<?= $esc($_POST['site_description'] ?? '') ?>" placeholder="A short description of your site">
        </label>
        <label>Admin Password
            <input type="password" name="password" required minlength="8" placeholder="At least 8 characters">
        </label>
        <label>Confirm Password
            <input type="password" name="password_confirm" required minlength="8">
        </label>
        <button type="submit">Configure</button>
    </form>
</div>
<?php endif; ?>

</body></html>
